[profile.default]
src = "contracts"
out = "out"
libs = ["lib"]
test = "test"

[profile.default.solc]
version = "0.8.20"
evm_version = "paris"

[profile.default.optimizer]
enabled = true
runs = 200

[profile.default.fuzz]
runs = 256
